version: '3'

services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    env_file:
      - .env

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '15432:80'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  gateway:
    build:
      context: ./
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - auth
      - meetups
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev api-gateway

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - meetups
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev auth

  meetups:
    build:
      context: ./
      dockerfile: ./apps/meetups/Dockerfile
      target: development
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev meetups
